name: app_vote
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  introduction_screen: 3.1.12
  qr_flutter: ^4.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  routemaster: ^1.0.1
  jwt_decoder: ^2.0.1
  http: ^1.2.0
  signature: ^5.5.0
  flutter_windowmanager: ^0.2.0
  qr_code_scanner: ^1.0.1
  no_screenshot: ^0.0.1+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: 5.1.0


flutter:

  uses-material-design: true

  assets:
    # - google_fonts/
    - assets/images/
    - assets/icons/

  fonts:
  - family: LatoFont
    fonts:
      - asset: google_fonts/Lato-Black.ttf
      - asset: google_fonts/Lato-BlackItalic.ttf
      - asset: google_fonts/Lato-Bold.ttf
      - asset: google_fonts/Lato-Regular.ttf
      - asset: google_fonts/Lato-Italic.ttf
      - asset: google_fonts/Lato-Light.ttf
