name: app_vote
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui layer
  cupertino_icons: 1.0.6
  google_fonts: 6.2.0
  introduction_screen: 3.1.12

  # data
  http: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: 5.1.0


flutter:

  uses-material-design: true

  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
